import { PrismaClient } from "@prisma/client"
const p = new PrismaClient()
const firms = [
  {name:"FTMO",slug:"ftmo",website:"https://ftmo.com",affiliateUrl:"https://ftmo.com/?ref=propro",category:"forex",programTypes:"2-Step",challengePriceRange:"$155-$1070",profitTarget:"10%",maxDrawdown:"10%",maxAccountSize:"$400K",trustpilotScore:4.6,reviewCount:5200,foundedYear:2015,country:"CZ",description:"Industry leader",features:"2-step,high profit split,global",rating:4.8,likesCount:95000,isNew:false},
  {name:"Topstep",slug:"topstep",website:"https://topstep.com",affiliateUrl:"https://topstep.com/?ref=propro",category:"futures",programTypes:"1-Step",challengePriceRange:"$49-$165",profitTarget:"None",maxDrawdown:"$2k-$4k",maxAccountSize:"$150K",trustpilotScore:4.7,reviewCount:1200,foundedYear:2012,country:"US",description:"Original futures prop firm",features:"1-step,no time limit,scaling",rating:4.7,likesCount:35000,isNew:false},
  {name:"Funding Pips",slug:"funding-pips",website:"https://fundingpips.com",affiliateUrl:"https://fundingpips.com/?ref=propro",category:"forex",programTypes:"1-Step,2-Step",challengePriceRange:"$95-$549",profitTarget:"8%",maxDrawdown:"10%",maxAccountSize:"$200K",trustpilotScore:4.7,reviewCount:1800,foundedYear:2022,country:"AE",description:"Fast-growing",features:"1-step,2-step,news trading,scaling",rating:4.7,likesCount:55000,isNew:false},
  {name:"Apex Trader Funding",slug:"apex-trader-funding",website:"https://apextraderfunding.com",affiliateUrl:"https://apextraderfunding.com/?ref=propro",category:"futures",programTypes:"1-Step",challengePriceRange:"$65-$147",profitTarget:"None",maxDrawdown:"$2k-$6k",maxAccountSize:"$300K",trustpilotScore:4.5,reviewCount:890,foundedYear:2021,country:"US",description:"Popular futures",features:"1-step,no time limit,residual",rating:4.5,likesCount:42000,isNew:false},
  {name:"FundedNext",slug:"fundednext",website:"https://fundednext.com",affiliateUrl:"https://fundednext.com/?ref=propro",category:"forex",programTypes:"1-Step,2-Step",challengePriceRange:"$79-$999",profitTarget:"10%",maxDrawdown:"8%",maxAccountSize:"$600K",trustpilotScore:4.5,reviewCount:2100,foundedYear:2022,country:"AE",description:"High accounts",features:"1-step,2-step,news trading,scaling",rating:4.6,likesCount:40000,isNew:false},
  {name:"The5ers",slug:"the5ers",website:"https://the5ers.com",affiliateUrl:"https://the5ers.com/?ref=propro",category:"forex",programTypes:"Growth Plan",challengePriceRange:"$80-$560",profitTarget:"8%",maxDrawdown:"6%",maxAccountSize:"$200K",trustpilotScore:4.6,reviewCount:950,foundedYear:2019,country:"IL",description:"Growth plan model",features:"growth plan,no time limit,scaling",rating:4.6,likesCount:22000,isNew:false},
  {name:"Tradeify",slug:"tradeify",website:"https://tradeify.co",affiliateUrl:"https://tradeify.co/?ref=69822",category:"futures",programTypes:"1-Step,Instant",challengePriceRange:"$45-$175",profitTarget:"8-10%",maxDrawdown:"5%",maxAccountSize:"$750K",trustpilotScore:4.6,reviewCount:164,foundedYear:2024,country:"US",description:"Modern futures",features:"1-step,instant funding,news trading",rating:4.7,likesCount:29665,isNew:false},
  {name:"Alpha Futures",slug:"alpha-futures",website:"https://alpha-futures.com",affiliateUrl:"https://app.alpha-futures.com/signup/MATCH/",category:"futures",programTypes:"1-Step",challengePriceRange:"$84-$225",profitTarget:"8-10%",maxDrawdown:"4-5%",maxAccountSize:"$750K",trustpilotScore:4.9,reviewCount:53,foundedYear:2024,country:"GB",description:"Premium futures",features:"1-step,low drawdown,high max account",rating:4.6,likesCount:46515,isNew:false},
  {name:"My Funded Futures",slug:"my-funded-futures",website:"https://myfundedfutures.com",affiliateUrl:"https://myfundedfutures.com/?ref=233",category:"futures",programTypes:"1-Step",challengePriceRange:"$75-$165",profitTarget:"10%",maxDrawdown:"5%",maxAccountSize:"$450K",trustpilotScore:4.9,reviewCount:236,foundedYear:2023,country:"US",description:"Fast-growing futures",features:"1-step,news trading",rating:4.5,likesCount:51823,isNew:false},
  {name:"E8 Markets",slug:"e8",website:"https://e8markets.com",affiliateUrl:"https://e8markets.com/?ref=propro",category:"futures",programTypes:"1-Step",challengePriceRange:"$85-$249",profitTarget:"8%",maxDrawdown:"5%",maxAccountSize:"$200K",trustpilotScore:4.5,reviewCount:200,foundedYear:2023,country:"US",description:"Fast-growing",features:"1-step,news trading",rating:4.5,likesCount:12000,isNew:false},
]
async function main() {
  console.log("Seeding " + firms.length + " firms...")
  for (const f of firms) {
    await p.firm.upsert({ where: { slug: f.slug }, update: f, create: f })
  }
  const c = await p.firm.count()
  console.log("Done! " + c + " firms in DB.")
}
main().catch(e => { console.error(e); process.exit(1) }).finally(() => p.$disconnect())
