import { NextResponse } from 'next/server'
import { prisma } from '@/lib/prisma'

export async function POST() {
  await prisma.firm.deleteMany()

  const firms = [
    {name:"Topstep",slug:"topstep",website:"https://topstep.com",affiliateUrl:"https://topstep.com/?ref=propro",category:"futures",programTypes:"No time limits on combines",challengePriceRange:"$49 - $375",profitTarget:"8%",maxDrawdown:"4%",maxAccountSize:"$150,000",trustpilotScore:4.5,reviewCount:3421,country:"USA",description:"Topstep",features:"No time limits on combines,100% profit split on Pro,Daily loss limit system",rating:4.5,likesCount:1847,isNew:false},
    {name:"Apex Trader Funding",slug:"apex-trader-funding",website:"https://apex-trader-funding.com",affiliateUrl:"https://apex-trader-funding.com/?ref=propro",category:"futures",programTypes:"1-Step",challengePriceRange:"$47 - $637",profitTarget:"8%",maxDrawdown:"5%",maxAccountSize:"$300,000",trustpilotScore:4.2,reviewCount:10523,country:"USA",description:"Apex Trader Funding",features:"No time limits,Same-day funding,Multiple account sizes",rating:4.2,likesCount:2103,isNew:false},
    {name:"My Funded Futures",slug:"my-funded-futures",website:"https://my-funded-futures.com",affiliateUrl:"https://my-funded-futures.com/?ref=propro",category:"futures",programTypes:"One-step evaluation",challengePriceRange:"$35 - $300",profitTarget:"10%",maxDrawdown:"5%",maxAccountSize:"$200,000",trustpilotScore:4.0,reviewCount:1876,country:"USA",description:"My Funded Futures",features:"Low entry prices,No time limit,One-step evaluation",rating:4.0,likesCount:845,isNew:false},
    {name:"Alpha Futures",slug:"alpha-futures",website:"https://alpha-futures.com",affiliateUrl:"https://alpha-futures.com/?ref=propro",category:"futures",programTypes:"1-Step",challengePriceRange:"$65 - $450",profitTarget:"8%",maxDrawdown:"5%",maxAccountSize:"$250,000",trustpilotScore:4.3,reviewCount:1234,country:"USA",description:"Alpha Futures",features:"Same-day funding,Scaling plans,Multiple platforms",rating:4.3,likesCount:567,isNew:false},
    {name:"Tradeify",slug:"tradeify",website:"https://tradeify.com",affiliateUrl:"https://tradeify.com/?ref=propro",category:"futures",programTypes:"1-Step",challengePriceRange:"$59 - $399",profitTarget:"8%",maxDrawdown:"4%",maxAccountSize:"$200,000",trustpilotScore:4.4,reviewCount:2341,country:"USA",description:"Tradeify",features:"No time limits,Real-time profit split,Multiple platforms",rating:4.4,likesCount:1023,isNew:false},
    {name:"Lucid Trading",slug:"lucid-trading",website:"https://lucid-trading.com",affiliateUrl:"https://lucid-trading.com/?ref=propro",category:"futures",programTypes:"Two-step evaluation",challengePriceRange:"$55 - $375",profitTarget:"10%",maxDrawdown:"5%",maxAccountSize:"$200,000",trustpilotScore:4.1,reviewCount:876,country:"USA",description:"Lucid Trading",features:"No time limit,Two-step evaluation,Daily loss limit",rating:4.1,likesCount:432,isNew:false},
    {name:"Orion Funded",slug:"orion-funded",website:"https://orion-funded.com",affiliateUrl:"https://orion-funded.com/?ref=propro",category:"futures",programTypes:"1-Step",challengePriceRange:"$49 - $349",profitTarget:"10%",maxDrawdown:"5%",maxAccountSize:"$150,000",trustpilotScore:4.2,reviewCount:1654,country:"USA",description:"Orion Funded",features:"No time limits,Same-day payouts,Scaling plan",rating:4.2,likesCount:678,isNew:false},
    {name:"The Trading Pit",slug:"the-trading-pit",website:"https://the-trading-pit.com",affiliateUrl:"https://the-trading-pit.com/?ref=propro",category:"futures",programTypes:"1-Step",challengePriceRange:"$99 - $599",profitTarget:"8%",maxDrawdown:"5%",maxAccountSize:"$200,000",trustpilotScore:4.3,reviewCount:2987,country:"Liechtenstein",description:"The Trading Pit",features:"Regulated prop firm,Multi-asset support,MT5 platform",rating:4.3,likesCount:1234,isNew:false},
    {name:"E8 Markets",slug:"e8-markets",website:"https://e8-markets.com",affiliateUrl:"https://e8-markets.com/?ref=propro",category:"futures",programTypes:"One-step Express",challengePriceRange:"$55 - $550",profitTarget:"10%",maxDrawdown:"5%",maxAccountSize:"$150,000",trustpilotScore:4.6,reviewCount:1456,country:"USA",description:"E8 Markets",features:"No time limits,One-step Express,Scaling plan",rating:4.6,likesCount:892,isNew:false},
    {name:"Atmos Funded",slug:"atmos-funded",website:"https://atmos-funded.com",affiliateUrl:"https://atmos-funded.com/?ref=propro",category:"futures",programTypes:"1-Step",challengePriceRange:"$45 - $325",profitTarget:"8%",maxDrawdown:"5%",maxAccountSize:"$200,000",trustpilotScore:3.9,reviewCount:678,country:"USA",description:"Atmos Funded",features:"No time limits,Competitive pricing,Multiple platforms",rating:3.9,likesCount:345,isNew:false},
    {name:"Lark Funding",slug:"lark-funding",website:"https://lark-funding.com",affiliateUrl:"https://lark-funding.com/?ref=propro",category:"futures",programTypes:"1-Step",challengePriceRange:"$39 - $299",profitTarget:"10%",maxDrawdown:"5%",maxAccountSize:"$150,000",trustpilotScore:4.0,reviewCount:543,country:"USA",description:"Lark Funding",features:"Affordable pricing,Scaling plan,No time limits",rating:4.0,likesCount:234,isNew:false},
    {name:"Moneta Funded",slug:"moneta-funded",website:"https://moneta-funded.com",affiliateUrl:"https://moneta-funded.com/?ref=propro",category:"futures",programTypes:"Two-step evaluation",challengePriceRange:"$59 - $399",profitTarget:"10%",maxDrawdown:"5%",maxAccountSize:"$200,000",trustpilotScore:4.1,reviewCount:432,country:"USA",description:"Moneta Funded",features:"No time limits,Two-step evaluation,Competitive profit splits",rating:4.1,likesCount:298,isNew:false},
    {name:"AquaFunded",slug:"aquafunded",website:"https://aquafunded.com",affiliateUrl:"https://aquafunded.com/?ref=propro",category:"futures",programTypes:"1-Step",challengePriceRange:"$49 - $349",profitTarget:"8%",maxDrawdown:"4%",maxAccountSize:"$200,000",trustpilotScore:4.2,reviewCount:876,country:"USA",description:"AquaFunded",features:"Same-day funding,No time limits,Scaling program",rating:4.2,likesCount:456,isNew:false},
    {name:"The Funded Trader",slug:"the-funded-trader",website:"https://the-funded-trader.com",affiliateUrl:"https://the-funded-trader.com/?ref=propro",category:"futures",programTypes:"Multiple evaluation types",challengePriceRange:"$25 - $799",profitTarget:"10%",maxDrawdown:"6%",maxAccountSize:"$200,000",trustpilotScore:3.5,reviewCount:4321,country:"USA",description:"The Funded Trader",features:"Low entry prices,Multiple evaluation types,Large account sizes",rating:3.5,likesCount:1567,isNew:false},
    {name:"FTMO",slug:"ftmo",website:"https://ftmo.com",affiliateUrl:"https://ftmo.com/?ref=propro",category:"forex",programTypes:"1-Step",challengePriceRange:"$155 - $1,140",profitTarget:"10%",maxDrawdown:"10%",maxAccountSize:"$400,000",trustpilotScore:4.6,reviewCount:12543,country:"Czech Republic",description:"FTMO",features:"Industry leader,Up to 90% profit split,Global recognition",rating:4.6,likesCount:3456,isNew:false},
    {name:"Funding Pips",slug:"funding-pips",website:"https://funding-pips.com",affiliateUrl:"https://funding-pips.com/?ref=propro",category:"forex",programTypes:"One-step Stellar",challengePriceRange:"$59 - $999",profitTarget:"8%",maxDrawdown:"8%",maxAccountSize:"$300,000",trustpilotScore:4.5,reviewCount:5678,country:"UK",description:"Funding Pips",features:"No time limits,Free retry,One-step Stellar",rating:4.5,likesCount:2345,isNew:false},
    {name:"FundedNext",slug:"fundednext",website:"https://fundednext.com",affiliateUrl:"https://fundednext.com/?ref=propro",category:"forex",programTypes:"Multiple evaluation models",challengePriceRange:"$69 - $999",profitTarget:"10%",maxDrawdown:"8%",maxAccountSize:"$200,000",trustpilotScore:4.4,reviewCount:4567,country:"UAE",description:"FundedNext",features:"Multiple evaluation models,Up to 90% profit split,No time limits on Stellar",rating:4.4,likesCount:1890,isNew:false},
    {name:"The5ers",slug:"the5ers",website:"https://the5ers.com",affiliateUrl:"https://the5ers.com/?ref=propro",category:"forex",programTypes:"1-Step",challengePriceRange:"$99 - $999",profitTarget:"8%",maxDrawdown:"10%",maxAccountSize:"$200,000",trustpilotScore:4.5,reviewCount:3210,country:"Israel",description:"The5ers",features:"Unique Growth Plan,Live support team,No time limits",rating:4.5,likesCount:1567,isNew:false},
    {name:"Blue Guardian",slug:"blue-guardian",website:"https://blue-guardian.com",affiliateUrl:"https://blue-guardian.com/?ref=propro",category:"forex",programTypes:"1-Step",challengePriceRange:"$99 - $999",profitTarget:"8%",maxDrawdown:"8%",maxAccountSize:"$200,000",trustpilotScore:4.4,reviewCount:2876,country:"UK",description:"Blue Guardian",features:"Fast payouts,Competitive spreads,MT4/MT5",rating:4.4,likesCount:1234,isNew:false},
    {name:"Audacity Capital",slug:"audacity-capital",website:"https://audacity-capital.com",affiliateUrl:"https://audacity-capital.com/?ref=propro",category:"forex",programTypes:"1-Step",challengePriceRange:"$149 - $749",profitTarget:"10%",maxDrawdown:"10%",maxAccountSize:"$200,000",trustpilotScore:4.2,reviewCount:1567,country:"UK",description:"Audacity Capital",features:"Performance-based scaling,Professional support,MT4/MT5",rating:4.2,likesCount:876,isNew:false},
    {name:"City Traders Imperium",slug:"city-traders-imperium",website:"https://city-traders-imperium.com",affiliateUrl:"https://city-traders-imperium.com/?ref=propro",category:"forex",programTypes:"1-Step",challengePriceRange:"$97 - $597",profitTarget:"10%",maxDrawdown:"8%",maxAccountSize:"$200,000",trustpilotScore:4.3,reviewCount:2345,country:"Australia",description:"City Traders Imperium",features:"Community focused,Educational resources,Scaling potential",rating:4.3,likesCount:998,isNew:false},
    {name:"Finotive Funding",slug:"finotive-funding",website:"https://finotive-funding.com",affiliateUrl:"https://finotive-funding.com/?ref=propro",category:"forex",programTypes:"One-step option",challengePriceRange:"$55 - $875",profitTarget:"8%",maxDrawdown:"6%",maxAccountSize:"$200,000",trustpilotScore:4.3,reviewCount:1876,country:"UK",description:"Finotive Funding",features:"One-step option,Up to 90% profit split,Affordable pricing",rating:4.3,likesCount:765,isNew:false},
    {name:"Fintokei",slug:"fintokei",website:"https://fintokei.com",affiliateUrl:"https://fintokei.com/?ref=propro",category:"forex",programTypes:"1-Step",challengePriceRange:"$115 - $1,100",profitTarget:"10%",maxDrawdown:"10%",maxAccountSize:"$300,000",trustpilotScore:4.5,reviewCount:1654,country:"Czech Republic",description:"Fintokei",features:"Speed Run option,High account sizes,Professional conditions",rating:4.5,likesCount:876,isNew:false},
    {name:"SurgeTrader",slug:"surgetrader",website:"https://surgetrader.com",affiliateUrl:"https://surgetrader.com/?ref=propro",category:"forex",programTypes:"One-step audition",challengePriceRange:"$99 - $999",profitTarget:"10%",maxDrawdown:"10%",maxAccountSize:"$200,000",trustpilotScore:4.1,reviewCount:2341,country:"USA",description:"SurgeTrader",features:"One-step audition,Up to 90% profit split,Same-day funding",rating:4.1,likesCount:1234,isNew:false},
    {name:"Funded Trading Plus",slug:"funded-trading-plus",website:"https://funded-trading-plus.com",affiliateUrl:"https://funded-trading-plus.com/?ref=propro",category:"forex",programTypes:"One-step available",challengePriceRange:"$69 - $799",profitTarget:"8%",maxDrawdown:"8%",maxAccountSize:"$200,000",trustpilotScore:4.2,reviewCount:1432,country:"UK",description:"Funded Trading Plus",features:"One-step available,Up to 85% profit split,No hidden rules",rating:4.2,likesCount:654,isNew:false},
    {name:"Ment Funding",slug:"ment-funding",website:"https://ment-funding.com",affiliateUrl:"https://ment-funding.com/?ref=propro",category:"forex",programTypes:"1-Step",challengePriceRange:"$79 - $899",profitTarget:"10%",maxDrawdown:"8%",maxAccountSize:"$250,000",trustpilotScore:4.3,reviewCount:1234,country:"UK",description:"Ment Funding",features:"High profit splits,Supportive management,Multiple account sizes",rating:4.3,likesCount:543,isNew:false},
    {name:"Smart Prop Trader",slug:"smart-prop-trader",website:"https://smart-prop-trader.com",affiliateUrl:"https://smart-prop-trader.com/?ref=propro",category:"forex",programTypes:"1-Step",challengePriceRange:"$49 - $749",profitTarget:"8%",maxDrawdown:"6%",maxAccountSize:"$200,000",trustpilotScore:4.0,reviewCount:987,country:"USA",description:"Smart Prop Trader",features:"Affordable pricing,Modern platform,No nonsense rules",rating:4.0,likesCount:432,isNew:false},
    {name:"Goat Funded Trader",slug:"goat-funded-trader",website:"https://goat-funded-trader.com",affiliateUrl:"https://goat-funded-trader.com/?ref=propro",category:"forex",programTypes:"1-Step",challengePriceRange:"$59 - $799",profitTarget:"8%",maxDrawdown:"8%",maxAccountSize:"$200,000",trustpilotScore:4.1,reviewCount:1123,country:"UK",description:"Goat Funded Trader",features:"No time limits,Rapid payouts,Up to 85% profit split",rating:4.1,likesCount:567,isNew:false},
    {name:"Elite Trader Funding",slug:"elite-trader-funding",website:"https://elite-trader-funding.com",affiliateUrl:"https://elite-trader-funding.com/?ref=propro",category:"forex",programTypes:"1-Step",challengePriceRange:"$89 - $899",profitTarget:"8%",maxDrawdown:"6%",maxAccountSize:"$200,000",trustpilotScore:4.2,reviewCount:1345,country:"USA",description:"Elite Trader Funding",features:"Professional-grade funding,Tight risk controls,MT4/MT5",rating:4.2,likesCount:654,isNew:false},
    {name:"For Traders",slug:"for-traders",website:"https://for-traders.com",affiliateUrl:"https://for-traders.com/?ref=propro",category:"forex",programTypes:"1-Step",challengePriceRange:"$75 - $875",profitTarget:"10%",maxDrawdown:"8%",maxAccountSize:"$200,000",trustpilotScore:4.0,reviewCount:876,country:"UK",description:"For Traders",features:"Trader-designed rules,Clean process,Competitive splits",rating:4.0,likesCount:345,isNew:false},
    {name:"BEM Funding",slug:"bem-funding",website:"https://bem-funding.com",affiliateUrl:"https://bem-funding.com/?ref=propro",category:"forex",programTypes:"1-Step",challengePriceRange:"$65 - $700",profitTarget:"8%",maxDrawdown:"6%",maxAccountSize:"$200,000",trustpilotScore:3.9,reviewCount:654,country:"UK",description:"BEM Funding",features:"Fast onboarding,Transparent conditions,Competitive pricing",rating:3.9,likesCount:234,isNew:false},
    {name:"Hola Prime",slug:"hola-prime",website:"https://hola-prime.com",affiliateUrl:"https://hola-prime.com/?ref=propro",category:"forex",programTypes:"Standard evaluations",challengePriceRange:"$89 - $999",profitTarget:"10%",maxDrawdown:"8%",maxAccountSize:"$200,000",trustpilotScore:3.8,reviewCount:432,country:"UK",description:"Hola Prime",features:"New innovative platform,Competitive pricing,Standard evaluations",rating:3.8,likesCount:187,isNew:false},
    {name:"Crypto Fund Trader",slug:"crypto-fund-trader",website:"https://crypto-fund-trader.com",affiliateUrl:"https://crypto-fund-trader.com/?ref=propro",category:"crypto",programTypes:"1-Step",challengePriceRange:"$49 - $699",profitTarget:"10%",maxDrawdown:"8%",maxAccountSize:"$200,000",trustpilotScore:4.4,reviewCount:2345,country:"USA",description:"Crypto Fund Trader",features:"Crypto-only focus,No time limits,Up to 90% profit split",rating:4.4,likesCount:1234,isNew:false},
    {name:"E8 Crypto",slug:"e8-crypto",website:"https://e8-crypto.com",affiliateUrl:"https://e8-crypto.com/?ref=propro",category:"crypto",programTypes:"Crypto evaluations",challengePriceRange:"$55 - $550",profitTarget:"10%",maxDrawdown:"5%",maxAccountSize:"$150,000",trustpilotScore:4.5,reviewCount:1234,country:"USA",description:"E8 Crypto",features:"Crypto evaluations,No time limits,Competitive profit splits",rating:4.5,likesCount:876,isNew:false},
    {name:"Trade The Pool",slug:"trade-the-pool",website:"https://trade-the-pool.com",affiliateUrl:"https://trade-the-pool.com/?ref=propro",category:"crypto",programTypes:"1-Step",challengePriceRange:"$79 - $795",profitTarget:"10%",maxDrawdown:"8%",maxAccountSize:"$100,000",trustpilotScore:4.1,reviewCount:1567,country:"USA",description:"Trade The Pool",features:"US-friendly,Crypto focused,Professional conditions",rating:4.1,likesCount:765,isNew:false},
    {name:"CFT",slug:"cft",website:"https://cft.com",affiliateUrl:"https://cft.com/?ref=propro",category:"crypto",programTypes:"1-Step",challengePriceRange:"$59 - $599",profitTarget:"10%",maxDrawdown:"8%",maxAccountSize:"$150,000",trustpilotScore:3.9,reviewCount:876,country:"UK",description:"CFT",features:"Crypto dedicated,Competitive pricing,Straightforward rules",rating:3.9,likesCount:432,isNew:false},
    {name:"Top One Trader",slug:"top-one-trader",website:"https://top-one-trader.com",affiliateUrl:"https://top-one-trader.com/?ref=propro",category:"crypto",programTypes:"Simple evaluation",challengePriceRange:"$49 - $499",profitTarget:"8%",maxDrawdown:"6%",maxAccountSize:"$100,000",trustpilotScore:3.7,reviewCount:543,country:"USA",description:"Top One Trader",features:"Affordable crypto funding,New platform,Simple evaluation",rating:3.7,likesCount:298,isNew:false},
    {name:"Maven",slug:"maven",website:"https://maven.com",affiliateUrl:"https://maven.com/?ref=propro",category:"instant",programTypes:"Instant funding,No challenge required",challengePriceRange:"$97 - $1,197",profitTarget:"10%",maxDrawdown:"10%",maxAccountSize:"$300,000",trustpilotScore:4.3,reviewCount:1876,country:"USA",description:"Maven",features:"Instant funding,No challenge required,Up to 90% profit split",rating:4.3,likesCount:1234,isNew:false},
    {name:"Alpha Capital",slug:"alpha-capital",website:"https://alpha-capital.com",affiliateUrl:"https://alpha-capital.com/?ref=propro",category:"instant",programTypes:"Instant funding available",challengePriceRange:"$79 - $979",profitTarget:"8%",maxDrawdown:"5%",maxAccountSize:"$200,000",trustpilotScore:4.1,reviewCount:1654,country:"UK",description:"Alpha Capital",features:"Instant funding available,Professional infrastructure,MT4/MT5",rating:4.1,likesCount:876,isNew:false},
    {name:"BrightFunded",slug:"brightfunded",website:"https://brightfunded.com",affiliateUrl:"https://brightfunded.com/?ref=propro",category:"instant",programTypes:"Instant funding path,Traditional evaluation",challengePriceRange:"$99 - $999",profitTarget:"8%",maxDrawdown:"6%",maxAccountSize:"$200,000",trustpilotScore:4.0,reviewCount:1234,country:"USA",description:"BrightFunded",features:"Hybrid funding options,Instant funding path,Traditional evaluation",rating:4.0,likesCount:654,isNew:false},
    {name:"FundedElite",slug:"fundedelite",website:"https://fundedelite.com",affiliateUrl:"https://fundedelite.com/?ref=propro",category:"instant",programTypes:"Instant and evaluation options",challengePriceRange:"$89 - $899",profitTarget:"10%",maxDrawdown:"8%",maxAccountSize:"$150,000",trustpilotScore:4.1,reviewCount:987,country:"USA",description:"FundedElite",features:"Instant and evaluation options,Elite trader focus,Competitive terms",rating:4.1,likesCount:543,isNew:false},
    {name:"Blueberry Funded",slug:"blueberry-funded",website:"https://blueberry-funded.com",affiliateUrl:"https://blueberry-funded.com/?ref=propro",category:"instant",programTypes:"Instant funding,Evaluation options",challengePriceRange:"$79 - $799",profitTarget:"10%",maxDrawdown:"10%",maxAccountSize:"$200,000",trustpilotScore:4.0,reviewCount:765,country:"UK",description:"Blueberry Funded",features:"Instant funding,Evaluation options,Crypto support",rating:4.0,likesCount:432,isNew:false},
    {name:"Volumetrica FX",slug:"volumetrica-fx",website:"https://volumetrica-fx.com",affiliateUrl:"https://volumetrica-fx.com/?ref=propro",category:"instant",programTypes:"Instant funding",challengePriceRange:"$59 - $699",profitTarget:"8%",maxDrawdown:"6%",maxAccountSize:"$100,000",trustpilotScore:3.8,reviewCount:543,country:"UK",description:"Volumetrica FX",features:"Volume-based model,Instant funding,High-frequency friendly",rating:3.8,likesCount:234,isNew:false},
    {name:"Hantec Trader",slug:"hantec-trader",website:"https://hantec-trader.com",affiliateUrl:"https://hantec-trader.com/?ref=propro",category:"hybrid",programTypes:"1-Step",challengePriceRange:"$99 - $999",profitTarget:"10%",maxDrawdown:"10%",maxAccountSize:"$200,000",trustpilotScore:4.2,reviewCount:1234,country:"UK",description:"Hantec Trader",features:"Regulated brokerage,Long-established,Hybrid model",rating:4.2,likesCount:765,isNew:false},
    {name:"Resolve Funding",slug:"resolve-funding",website:"https://resolve-funding.com",affiliateUrl:"https://resolve-funding.com/?ref=propro",category:"instant",programTypes:"Instant access",challengePriceRange:"$69 - $769",profitTarget:"10%",maxDrawdown:"8%",maxAccountSize:"$150,000",trustpilotScore:4.0,reviewCount:876,country:"USA",description:"Resolve Funding",features:"Instant access,No time limits,Quick onboarding",rating:4.0,likesCount:456,isNew:false},
    {name:"Breakout Funding",slug:"breakout-funding",website:"https://breakout-funding.com",affiliateUrl:"https://breakout-funding.com/?ref=propro",category:"hybrid",programTypes:"Instant options",challengePriceRange:"$49 - $649",profitTarget:"8%",maxDrawdown:"6%",maxAccountSize:"$200,000",trustpilotScore:4.1,reviewCount:1123,country:"USA",description:"Breakout Funding",features:"Hybrid funding,Instant options,Momentum-friendly",rating:4.1,likesCount:567,isNew:false},
    {name:"ThinkCapital",slug:"thinkcapital",website:"https://thinkcapital.com",affiliateUrl:"https://thinkcapital.com/?ref=propro",category:"hybrid",programTypes:"1-Step",challengePriceRange:"$149 - $1,499",profitTarget:"8%",maxDrawdown:"10%",maxAccountSize:"$300,000",trustpilotScore:4.4,reviewCount:2341,country:"USA",description:"ThinkCapital",features:"Premium service,Large account sizes,Performance bonuses",rating:4.4,likesCount:1456,isNew:false},
    {name:"Fidelcrest",slug:"fidelcrest",website:"https://fidelcrest.com",affiliateUrl:"https://fidelcrest.com/?ref=propro",category:"hybrid",programTypes:"1-Step",challengePriceRange:"$79 - $1,099",profitTarget:"8%",maxDrawdown:"10%",maxAccountSize:"$400,000",trustpilotScore:4.2,reviewCount:2345,country:"UK",description:"Fidelcrest",features:"Long-standing firm,Large account sizes,Pro Trader program",rating:4.2,likesCount:1234,isNew:false},
    {name:"Funded Engineer",slug:"funded-engineer",website:"https://funded-engineer.com",affiliateUrl:"https://funded-engineer.com/?ref=propro",category:"instant",programTypes:"Instant funding",challengePriceRange:"$49 - $549",profitTarget:"8%",maxDrawdown:"5%",maxAccountSize:"$100,000",trustpilotScore:3.8,reviewCount:432,country:"USA",description:"Funded Engineer",features:"Algorithmic friendly,Instant funding,Quant-focused",rating:3.8,likesCount:298,isNew:false},
    {name:"Earn2Trade",slug:"earn2trade",website:"https://earn2trade.com",affiliateUrl:"https://earn2trade.com/?ref=propro",category:"futures",programTypes:"1-Step",challengePriceRange:"$199 - $999",profitTarget:"10%",maxDrawdown:"6%",maxAccountSize:"$200,000",trustpilotScore:4.3,reviewCount:2341,country:"USA",description:"Earn2Trade",features:"Trader Career Path,Educational focus,Gauntlet integration",rating:4.3,likesCount:1123,isNew:false},
    {name:"Leeloo Trading",slug:"leeloo-trading",website:"https://leeloo-trading.com",affiliateUrl:"https://leeloo-trading.com/?ref=propro",category:"futures",programTypes:"One-step option",challengePriceRange:"$39 - $599",profitTarget:"8%",maxDrawdown:"5%",maxAccountSize:"$200,000",trustpilotScore:4.1,reviewCount:1543,country:"USA",description:"Leeloo Trading",features:"Competitive pricing,Same-day funding,One-step option",rating:4.1,likesCount:678,isNew:false},
    {name:"Tradiac",slug:"tradiac",website:"https://tradiac.com",affiliateUrl:"https://tradiac.com/?ref=propro",category:"forex",programTypes:"Two-step evaluation",challengePriceRange:"$99 - $1,099",profitTarget:"10%",maxDrawdown:"10%",maxAccountSize:"$200,000",trustpilotScore:4.0,reviewCount:1234,country:"UK",description:"Tradiac",features:"Two-step evaluation,Up to 80% profit split,MT4/MT5",rating:4.0,likesCount:456,isNew:false},
  ]
  try {
    let count = 0
    for (const f of firms) { await prisma.firm.upsert({ where: { slug: f.slug }, update: f, create: f }); count++ }
    return NextResponse.json({ seeded: count, total: await prisma.firm.count() })
  } catch (e) { return NextResponse.json({ error: String(e) }, { status: 500 }) }
}